version: "3"
services:

  php-hello-world:
    image: lmeadows/php-hello-world
    ports:
      - "4000"
    deploy:
      replicas: 2
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
